---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Remove old logs
    command: rm -f /var/log/kibana/kibana.log

  - name: Run Kibana
    shell: cd /usr/share/kibana; export Environment=KBN_HOME=/usr/share/kibana; Environment=KBN_PATH_CONF=/etc/kibana; nohup /usr/share/kibana/bin/kibana --logging.dest="/var/log/kibana/kibana.log" --pid.file="/run/kibana/kibana.pid" --allow-root & sleep 10

  - name: Analyze logs
    shell: cat /var/log/kibana/kibana.log
    register: service_log

  - name: Service Check
    assert:
      that: '"http server running at http://0.0.0.0:5601" in service_log.stdout'

  - name: Kill Kibana
    shell: pkill -9 node
